/// <reference lib="webworker" />
//
// Single-threaded Wasm miner worker.
//
// NOTE: this file imports from `./pkg/pohe_wasm_core.js`, which is generated
// by `wasm-pack build --target web --out-dir ../client/src/wasm/pkg` in the
// wasm-core crate. Run that command before `pnpm dev`.
//
// The worker runs the VDF in ~30 chunks so it can post progress frames to the
// main thread without blocking. Each chunk is further split into
// `checkpoint_every`-sized sub-chunks so every checkpoint boundary is
// captured, matching the output of a single continuous `run_chain` call.

// @ts-expect-error generated by wasm-pack
import init, { mine_chunk } from "./pkg/pohe_wasm_core";

interface StartMsg {
  type: "start";
  seed_hex: string;
  difficulty: number;
  checkpoint_every: number;
}

type IncomingMsg = StartMsg;

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function bytesToHex(b: Uint8Array): string {
  let s = "";
  for (let i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, "0");
  return s;
}

let wasmReady: Promise<unknown> | null = null;

const PROGRESS_CHUNKS = 30;

self.onmessage = async (ev: MessageEvent<IncomingMsg>) => {
  try {
    if (ev.data.type !== "start") return;
    const { seed_hex, difficulty, checkpoint_every } = ev.data;

    wasmReady ??= init();
    await wasmReady;

    // Compute state_0 = SHA256(seed) — the initial state before any VDF
    // iteration. This matches `run_chain`'s starting point.
    const seedBytes = hexToBytes(seed_hex);
    const state0 = new Uint8Array(
      await crypto.subtle.digest("SHA-256", seedBytes)
    );

    // Emit a synthetic progress tick so the HUD animation starts immediately.
    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "progress",
      rounds: 0,
      digest_prefix: bytesToHex(state0).slice(0, 16),
    });

    // --- build sub-chunks aligned to checkpoint boundaries ---
    // Each sub-chunk is exactly `checkpoint_every` rounds (except the last,
    // which may be smaller). This guarantees a checkpoint is captured at
    // every `checkpoint_every` boundary, matching `run_chain`'s output.
    const subChunks: number[] = [];
    let remaining = difficulty;
    while (remaining > 0) {
      const sz = Math.min(checkpoint_every, remaining);
      subChunks.push(sz);
      remaining -= sz;
    }

    // Group sub-chunks so we emit ~PROGRESS_CHUNKS progress updates.
    const subChunksPerProgress = Math.max(
      1,
      Math.ceil(subChunks.length / PROGRESS_CHUNKS)
    );

    const checkpoints: string[] = [bytesToHex(state0)];
    let state = state0;
    let currentRound = 0;

    for (let i = 0; i < subChunks.length; ) {
      const batchEnd = Math.min(i + subChunksPerProgress, subChunks.length);

      // Run all sub-chunks in this batch synchronously (no yield). Each
      // sub-chunk is a single Wasm call; the batch as a whole is small
      // enough to not block the main thread perceptibly.
      for (let j = i; j < batchEnd; j++) {
        state = mine_chunk(
          state,
          BigInt(currentRound),
          BigInt(subChunks[j])
        );
        currentRound += subChunks[j];

        if (currentRound % checkpoint_every === 0) {
          checkpoints.push(bytesToHex(state));
        }
      }

      i = batchEnd;

      (self as DedicatedWorkerGlobalScope).postMessage({
        type: "progress",
        rounds: currentRound,
        digest_prefix: bytesToHex(state).slice(0, 16),
      });

      // Yield to the event loop so queued messages flush to the main thread.
      if (currentRound < difficulty) {
        await new Promise((r) => setTimeout(r, 0));
      }
    }

    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "done",
      seed_hex,
      difficulty,
      checkpoint_every,
      final_state_hex: bytesToHex(state),
      checkpoints_hex: checkpoints,
    });
  } catch (err) {
    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
};

export {};
