/// <reference lib="webworker" />
//
// Single-threaded Wasm miner worker.
//
// NOTE: this file imports from `./pkg/pohe_wasm_core.js`, which is generated
// by `wasm-pack build --target web --out-dir ../client/src/wasm/pkg` in the
// wasm-core crate. Run that command before `pnpm dev`.
//
// The worker runs the VDF in *chunks* so it can post progress frames to the
// main thread without blocking. Each chunk uses `mine()` over a small slice
// and threads the final state into the next slice (TODO post-MVP).
// For the skeleton, we run it in one call and post a single done event.

// @ts-expect-error generated by wasm-pack
import init, { mine } from "./pkg/pohe_wasm_core";

interface StartMsg {
  type: "start";
  seed_hex: string;
  difficulty: number;
  checkpoint_every: number;
}

type IncomingMsg = StartMsg;

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

function bytesToHex(b: Uint8Array): string {
  let s = "";
  for (let i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, "0");
  return s;
}

let wasmReady: Promise<unknown> | null = null;

self.onmessage = async (ev: MessageEvent<IncomingMsg>) => {
  try {
    if (ev.data.type !== "start") return;
    const { seed_hex, difficulty, checkpoint_every } = ev.data;

    wasmReady ??= init();
    await wasmReady;

    // Emit one synthetic progress tick so the HUD animation starts immediately.
    // A future version will chunk the loop to emit real progress.
    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "progress",
      rounds: 0,
      digest_prefix: seed_hex.slice(0, 16),
    });

    const seed = hexToBytes(seed_hex);
    const bundle = mine(seed, BigInt(difficulty), BigInt(checkpoint_every));

    const final_state: Uint8Array = bundle.final_state;
    const checkpoints_flat: Uint8Array = bundle.checkpoints;
    const cps: string[] = [];
    for (let i = 0; i < checkpoints_flat.length; i += 32) {
      cps.push(bytesToHex(checkpoints_flat.slice(i, i + 32)));
    }

    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "done",
      seed_hex,
      difficulty,
      checkpoint_every,
      final_state_hex: bytesToHex(final_state),
      checkpoints_hex: cps,
    });
  } catch (err) {
    (self as DedicatedWorkerGlobalScope).postMessage({
      type: "error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
};

export {};
